

image:
  repository: jbgwese/${{values.app_name}}
  pullPolicy: IfNotPresent
  tag: ${{values.app_name}}-${{values.app_env}-latest


serviceAccount:
  create: false
  annotations: {}
  name: ""

service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: ${{values.app_name}}-${{values.app_env}p.test.com
      paths:
        - path: /
          pathType: Prefix
resources:
  requests:
    cpu: 50m
    memory: 50M

httpRoute:
  enabled: false

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

readinessProbe:
  httpGet:
    path: /api/v1/healthz
    port: 5000
  initialDelaySeconds: 5
  periodSeconds: 10

livenessProbe:
  httpGet:
    path: /api/v1/healthz
    port: 5000
  initialDelaySeconds: 15
  periodSeconds: 20